check ci

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -37,6 +37,17 @@ jobs:
           cd test && npm ci && cd ..
           npm t
 
+      - name: Check lcov.info exists and print contents
+        run: |
+          pwd
+          if [ -f ./test/coverage/lcov.info ]; then
+            echo "✅ lcov.info found"
+            cat ./test/coverage/lcov.info
+          else
+            echo "❌ lcov.info NOT FOUND"
+            exit 1
+          fi
+
       - name: Upload coverage results to Coveralls
         uses: coverallsapp/github-action@master
         with:
